#docker build -t simpleradius -f ./SimpleRadius/docker/Dockerfile-armv7 .

FROM maxchen021/archlinux:latest-armv7
EXPOSE 443 1812 1812/udp

#install the packages here, so future code changes will require only a small change
RUN pacman -Sy \
&& pacman -S --noconfirm --needed apache \
&& pacman -S --noconfirm --needed php \
&& pacman -S --noconfirm --needed php-apache \
&& pacman -S --noconfirm --needed sqlite \
&& pacman -S --noconfirm --needed php-sqlite \
&& pacman -S --noconfirm --needed php-mcrypt \
&& pacman -S --noconfirm --needed tar \
&& pacman -S --noconfirm --needed openssl \
&& pacman -S --noconfirm --needed mono \
&& pacman -S --noconfirm --needed pkg-config \
&& pacman -S --noconfirm --needed freeradius \
&& pacman -S --noconfirm --needed sudo \
&& pacman -Scc --noconfirm

COPY SimpleRadius /tmp/SimpleRadius/

RUN cd /tmp/SimpleRadius \
&& ./installation/arch_linux/install.sh \
&& cp /tmp/SimpleRadius/docker/docker_entrypoint.sh /docker_entrypoint.sh \
&& chmod 755 /docker_entrypoint.sh \
&& rm -rf /tmp/SimpleRadius \
&& rm /var/run/radiusd/radiusd.pid


ENTRYPOINT ["/docker_entrypoint.sh"]